jajan_jogja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zoya.urls')),
    path('review/', include('reviews.urls')),
    path('search/', include('nabeel.urls')),
    path('auth/', include('main.urls')),
    path('restaurant/', include('marco.urls')),
    path('food_plans/', include('reksa.urls')),
    path('adm/', include('alfian.urls')),
    path('auth_api/', include('authentication.urls')),
]

main/urls.py
from django.urls import path, include
from main.views import show_main
from django.urls import path
from main.views import login_user, logout_user, show_main, register, profile, edit_profile_flutter

app_name = 'main'

urlpatterns = [
    path('login/', login_user, name='login_user'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
    path('profile-flutter/', edit_profile_flutter, name='profile'),
]

zoya/urls.py
from django.urls import path
from zoya.views import show_main, show_json_tempat, show_json_forum, add_forum_entry_ajax, get_user_by_id, get_current_user_id, delete_forum_entry, show_json_makanan, edit_forum_entry, create_forum_flutter, edit_forum_flutter, delete_forum_flutter, show_json_user_by_id, show_json_current_user, show_json_forum_by_id

app_name = 'zoya'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('json-tempat/', show_json_tempat, name='show_json_tempat'),
    path('json-forum/', show_json_forum, name='show_json_forum'),
    path('json-forum/<uuid:id>/', show_json_forum_by_id, name='show_json_forum_by_id'),
    path("json-makanan/", show_json_makanan, name="show_json_makanan"),
    path('edit-forum/<uuid:id>/', edit_forum_entry, name='edit_forum_entry'),
    path('delete-forum/<uuid:id>/', delete_forum_entry, name='delete_forum_entry'),
    path('create-forum-entry-ajax', add_forum_entry_ajax, name='add_forum_entry_ajax'),
    path('get-user/<int:user_id>/', get_user_by_id, name='get_user_by_id'),
    path('json-user/<int:user_id>/', show_json_user_by_id, name='show_json_user_by_id'),
    path('get-current-user-id/', get_current_user_id, name='get_current_user_id'),
    path('json-current-user/', show_json_current_user, name='show_json_current_user'),
    path('create-flutter/', create_forum_flutter, name='create_forum_flutter'),
    path('edit-flutter/<uuid:forum_id>/', edit_forum_flutter, name='edit_forum_flutter'),
    path('delete-flutter/<uuid:forum_id>/', delete_forum_flutter, name='delete_forum_flutter'),
]

zoya/models.py
from django.db import models
from decimal import Decimal
import uuid
from django.contrib.auth.models import User
from django.db.models import Avg


class CommunityForum(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateField(auto_now_add=True)
    comment = models.TextField()

    def __str__(self):
        return self.comment

class TempatKuliner(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nama = models.CharField(max_length=255)
    description = models.TextField()
    alamat = models.CharField(max_length=255)  
    longitude = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    jamBuka = models.TimeField()
    jamTutup = models.TimeField()
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True, default=None)
    foto_link = models.TextField(default="https://cdn.britannica.com/36/123536-050-95CB0C6E/Variety-fruits-vegetables.jpg")
    variasi = models.ManyToManyField('Variasi', related_name='tempat_kuliner_set')

    def update_rating(self):
        result = self.reviews.aggregate(average=Avg('rating'))
        self.rating = Decimal(result['average']) if result['average'] is not None else None
        self.save()

    def __str__(self):
        return self.nama


class Makanan(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tempat_kuliner = models.ForeignKey(TempatKuliner, on_delete=models.CASCADE, related_name='makanan', null=True)
    nama = models.CharField(max_length=255)
    description = models.TextField()  
    harga = models.IntegerField()
    foto_link = models.TextField(default="https://cdn.britannica.com/36/123536-050-95CB0C6E/Variety-fruits-vegetables.jpg")

    def __str__(self):
        return self.nama
    

class Variasi(models.Model):
    nama = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nama

zoya/forms.py
from django.forms import ModelForm
from zoya.models import CommunityForum
from django.utils.html import strip_tags

class CommunityForumForm(ModelForm):
    class Meta:
        model = CommunityForum
        fields = ["comment"]
        
    def clean_comment(self):
        comment = self.cleaned_data["comment"]
        return strip_tags(comment)

zoya/views.py
import json
from django.shortcuts import render, reverse
from zoya.models import TempatKuliner, CommunityForum, Makanan, Variasi
from zoya.forms import CommunityForumForm
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_http_methods
from django.utils.html import strip_tags
from django.contrib.auth.models import User
from django.http import JsonResponse

def show_main(request):
    makanan = Makanan.objects.all()[:15]
    variasi = Variasi.objects.all()

    context = {
        'makanan': makanan,
        'variasi': variasi,
    }

    return render(request, 'landing.html', context)

def show_json_tempat(request):
    data = TempatKuliner.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_makanan(request):
    data = Makanan.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_forum(request):
    data = CommunityForum.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_forum_by_id(request, id):
    try:
        forum = CommunityForum.objects.get(pk=id)
        return JsonResponse({"comment": forum.comment})
    except CommunityForum.DoesNotExist:
        return JsonResponse({"error": "Forum not found"}, status=404)

@csrf_exempt
@require_http_methods(["DELETE"])
def delete_forum_entry(request, id):
    if request.user.is_authenticated:
        try:
            forum_entry = CommunityForum.objects.get(pk=id, user=request.user)
            forum_entry.delete()
            return HttpResponse(status=204)
        except CommunityForum.DoesNotExist:
            return HttpResponse(status=404)
    return HttpResponse(status=403)

def edit_forum_entry(request, id):
    mood = CommunityForum.objects.get(pk = id)

    form = CommunityForumForm(request.POST or None, instance=mood)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('zoya:show_main'))

    context = {'form': form}
    return render(request, "edit_forum.html", context)

@csrf_exempt
@require_POST
def add_forum_entry_ajax(request):
    comment = strip_tags(request.POST.get("comment"))
    user = request.user
    if not user.is_authenticated:
        return JsonResponse({'error': 'User not authenticated'}, status=403)

    new_forum = CommunityForum(
        comment=comment,
        user=user
    )
    new_forum.save()

    return HttpResponse(b"CREATED", status=201)

def get_user_by_id(request, user_id):
    user = User.objects.get(pk=user_id)
    data = {
        "username": user.username,
    }
    return JsonResponse(data)

def get_current_user_id(request):
    if request.user.is_authenticated:
        return JsonResponse({'user_id': request.user.id})
    else:
        return JsonResponse({'user_id': None})

def show_json_user_by_id(request, user_id, json=True):
    user = User.objects.get(pk=user_id)
    user_json = {
        "id": user_id,
        "username": user.username,
    }

    if json:
        return JsonResponse(user_json, safe=False, status=200)
    return user_json

def show_json_current_user(request, json=True):
    if request.user.is_authenticated:
        user_json = {
            "id": request.user.id,
            "username": request.user.username,
            "is_admin": request.user.is_staff or request.user.is_superuser,
            "email": request.user.email
        }

        if json:
            return JsonResponse(user_json, safe=False, status=200)
        return user_json
    else:
        return JsonResponse({'id': None})

@csrf_exempt
def create_forum_flutter(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return JsonResponse({"status": "error", "message": "You must be logged in to create a forum."}, status=403)

        data = json.loads(request.body)
        user=request.user
        comment=data["comment"]

        if not comment or comment == "":
            return JsonResponse({"status": "error", "message": "All fields must be filled."}, status=400)

        new_forum = CommunityForum.objects.create(
            user=user,
            comment=comment
        )

        new_forum.save()

        return JsonResponse({"status": "success", "message": "Comment successfully created."}, status=201)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method."}, status=400)
    
@csrf_exempt
def edit_forum_flutter(request, forum_id):
    if request.method == "POST":
        if not request.user.is_authenticated:
            return JsonResponse({"status": "error", "message": "You must be logged in to create a forum."}, status=403)

        data = json.loads(request.body)
        comment=data["comment"]

        if not comment or comment == "":
            return JsonResponse({"status": "error", "message": "All fields must be filled."}, status=400)

        community_forum = CommunityForum.objects.get(id=forum_id)

        if community_forum.user != request.user:
            return JsonResponse({"status": "error", "message": "You are not authorized to edit this comment."}, status=403)
        
        community_forum.comment = comment
        community_forum.save()

        return JsonResponse({"status": "success", "message": "Comment successfully edited."}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method."}, status=400)

@csrf_exempt
def delete_forum_flutter(request, forum_id):
    if request.method == "GET":
        if not request.user.is_authenticated:
            return JsonResponse({"status": "error", "message": "You must be logged in to create a forum."}, status=403)

        community_forum = CommunityForum.objects.get(id=forum_id)

        if community_forum.user != request.user:
            return JsonResponse({"status": "error", "message": "You are not authorized to delete this comment."}, status=403)

        community_forum.delete()

        return JsonResponse({"status": "success", "message": "Comment successfully deleted."}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method."}, status=400)

zoya/templates/edit_forum.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-white">
  <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
    <h1 class="py-5 text-3xl font-bold text-center text-darkOrange">Edit Forum Comment</h1>
  
    <div class="bg-white rounded-[40px] p-6 form-style border-4 border-darkOrange">
      <form method="POST">
          {% csrf_token %}
          {% for field in form %}
              <div class="flex flex-col">
                  <label for="{{ field.id_for_label }}" class="font-semibold text-darkOrange text-2xl">
                      {{ field.label }}
                  </label>
                  <div class="w-full flex flex-col py-3">
                      {{ field }}
                  </div>
                  {% if field.help_text %}
                      <p class="mt-1 text-sm text-grey">{{ field.help_text }}</p>
                  {% endif %}
                  {% for error in field.errors %}
                      <p class="mt-1 text-sm text-orange">{{ error }}</p>
                  {% endfor %}
              </div>
          {% endfor %}
          <div class="flex flex-row space-x-4">
              <button href="" class="bg-orange text-white text-[18px] py-2 rounded-[10px] hover:bg-darkOrange w-1/2">Cancel</button>
              <button type="submit" class="bg-yellow text-white text-[18px] py-2 rounded-[10px] hover:bg-darkYellow w-1/2">Save</button>
          </div>  
      </form>
    </div>
  </div>
</div>
{% endblock %}

zoya/templates/landing.html
{% extends "base.html" %}
{% load static %}
{% block content %}

{% include 'navbar.html' with page="home"  %}

<style>
    @keyframes pulse {
        0%, 100% {
            transform: scale(1);
        }
        50% {
            transform: scale(1.04);
        }
    }

    .pulsating {
        transition: transform 0.5s ease, opacity 0.3s ease;
    }

    .pulsating:hover {
        animation: pulse 3s cubic-bezier(0.4, 0, 0.2, 1) infinite;
    }
</style>

<div class="flex flex-col justify-center items-center my-28 w-screen">
    <!-- Carousel -->
    <div id="default-carousel" class="lg:w-[70vw] xl:w-[60vw] w-[95vw] h-[525px] relative mx-auto" data-carousel="slide">
        <div class="lg:w-[70vw] xl:w-[60vw] w-[95vw] h-[481px] left-0 top-0 absolute overflow-hidden rounded-[50px] border-4 border-darkYellow px-4">
            {% if makanan.count == 0 %}
            <p class="text-center">No images available</p>
            {% elif makanan.count == 1 %}
                {% for item in makanan %}
                    <a href="restaurant/{{ item.tempat_kuliner.pk }}">
                        <img src="{{ item.foto_link }}" class="absolute block w-full h-full object-cover -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="{{item.nama}}">
                        <div class="left-[50px] top-[307px] lg:top-[287px] absolute text-[#c98809] text-[32px] lg:text-6xl font-normal font-['Jockey One'] leading-tight" style="text-shadow: 2px 2px 4px rgba(56, 7, 7, 0.7);">{{item.nama}}</div>
                        <div class="left-[53px] top-[343px] absolute text-[#7c1d04] text-[27px] lg:text-4xl font-normal font-['Jockey One'] leading-tight" style="text-shadow: 2px 2px 4px rgba(56, 7, 7, 0.7);">{{item.tempat_kuliner.nama}}</div>
                    </a>
                {% endfor %}
            {% else %}
                {% for item in makanan %}
                    <a href="restaurant/{{ item.tempat_kuliner.pk }}" class="hidden duration-700 ease-in-out" data-carousel-item>
                        <img src="{{ item.foto_link }}" class="absolute block w-full h-full object-cover -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2" alt="{{item.nama}}">
                        <div class="left-[50px] top-[307px] lg:top-[287px] absolute text-[#c98809] text-[32px] lg:text-6xl font-normal font-['Jockey One'] leading-tight" style="text-shadow: 2px 2px 4px rgba(56, 7, 7, 0.7);">{{item.nama}}</div>
                        <div class="left-[53px] top-[343px] absolute text-[#7c1d04] text-[27px] lg:text-4xl font-normal font-['Jockey One'] leading-tight" style="text-shadow: 2px 2px 4px rgba(56, 7, 7, 0.7);">{{item.tempat_kuliner.nama}}</div>
                    </a>
                {% endfor %}
            {% endif %}

            <img src="{% static 'images/elemen_jogja.png' %}" class="absolute object-cover top-0 w-full h-full" style="pointer-events: none;">
        </div>

        {% if makanan.count > 1 %}
        <!-- right arrow -->
        <button class="w-[41px] h-[60px] z-[801] right-[15px] lg:-right-[60px] top-[214px] absolute text-darkYellow leading-[79.25px]" data-carousel-next>
            <svg viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <line x1="5" y1="12" x2="19" y2="12" />  <polyline points="12 5 19 12 12 19" /></svg>
        </button>

        <!-- left arrow -->
        <button class="w-[41px] h-[60px] z-[801] left-[15px] lg:-left-[60px] top-[214px] absolute text-darkYellow leading-[79.25px]" data-carousel-prev>
            <svg viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <line x1="19" y1="12" x2="5" y2="12" />  <polyline points="12 19 5 12 12 5" /></svg>
        </button>
        {% endif %}
    </div>

    <!-- See More Button -->
    <a href="#seemore" id="seemore" class="w-[200px] h-[65px] z-[800] bg-[#ebe9e1] rounded-[158px] -translate-y-[80px] border-l-8 border-r-8 border-[#c98809] hover:shadow-lg hover:scale-105">
        <div class="text-center text-[#7c1d04] text-[34px] lg:text-[px] font-normal font-['Jockey One'] leading-[69.25px]">See More!</div>
    </a>

    <div class="text-darkYellow text-[25px] md:text-[36px] font-['Jockey One']">Looking for places to eat in Jogja?</div>

    <!-- Cards Tempat -->
    <div id="tempat_kuliner_cards"></div>

    <!-- Community Forum -->
    <div class="my-28 w-screen flex flex-col items-center">
        <div class="w-[80vw] lg:w-[55vw] xl:w-[45vw]">
            <h2 class="text-darkYellow text-[25px] md:text-[36px] font-['Jockey One'] text-center mb-8">Community Forum</h2>

            <!-- New Post Form -->
            <div class="bg-[#ebe9e1] border-4 border-[#c88709] rounded-[20px] p-6 mb-6">
                <h3 class="text-[#7c1d04] text-[20px] lg:text-[24px] font-['Jockey One'] mb-4">Share Your Experience</h3>
                <form id="new_post_forum" class="flex flex-col space-y-4">
                    <textarea id="user_comment" name="comment" class="border-2 border-darkYellow p-2 rounded-[10px] text-[15px] text-[#7a7a7a]" rows="4" placeholder="Write your comment..." required></textarea>
                    <button id="submitForumEntry" type="submit" form="new_post_forum" class="bg-darkOrange text-white text-[18px] py-2 rounded-[10px] hover:bg-orange">Post</button>
                </form>
            </div>

            <!-- Forum Discussion Section -->
            <div class="bg-[#f3f3f3] border-4 border-[#c88709] rounded-[20px] p-6">
                <h3 class="text-[#7c1d04] text-[20px] lg:text-[24px] font-['Jockey One'] mb-4">Discussion</h3>
                <div id="forum_posts" class="space-y-4"></div>
            </div>
        </div>
    </div>
</div>

<!-- Include Flowbite JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
<script>
    function addForum() {
        const form = document.getElementById('new_post_forum');

        // Check if the form is valid before proceeding
        if (form.checkValidity()) {
            fetch("{% url 'zoya:add_forum_entry_ajax' %}", {
                method: "POST",
                body: new FormData(form),
            })
            .then(response => {
                if (response.ok) {
                    refreshCommunityForum(); // Refresh the forum posts after a successful response
                    form.reset(); // Reset the form after successful submission
                    document.querySelector("[data-modal-toggle='crudModal']").click();
                } else if (response.status === 403) {
                    alert('You must be logged in to add a forum entry. Please log in and try again.'); // Provide feedback to the user
                } else {
                    // Handle error response if needed
                    console.error('Error:', response.statusText);
                }
            })
            .catch(error => {
                console.error('Fetch error:', error);
            });
        } else {
            // Trigger validation messages
            form.reportValidity(); // This shows the browser's validation messages
        }

        return false; // Prevent default form submission
    }

    document.getElementById("submitForumEntry").onclick = addForum

    async function deleteForumEntry(forumId) {
        const response = await fetch(`/delete-forum/${forumId}/`, {
            method: "DELETE",
        });

        if (response.ok) {
            refreshCommunityForum();
        } else {
            alert("Failed to delete the comment.");
        }
    }

    async function getTempatKuliner(){
        return fetch("{% url 'zoya:show_json_tempat' %}").then((res) => res.json())
    }

    async function refreshTempatKuliner() {
        document.getElementById("tempat_kuliner_cards").innerHTML = "";
        document.getElementById("tempat_kuliner_cards").className = "";
        const tempatKuliner = await getTempatKuliner();

        let htmlString = "";
        let classNameString = "";

        if (tempatKuliner.length === 0) {
            classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
            htmlString = `
                <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                    <p class="text-center text-grey mt-4 font-semibold">Nothing to see here...</p>
                </div>
            `;
        }
        else {
            classNameString = "py-3 gap-5 grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2"
            tempatKuliner.forEach((item) => {
                // const nama = DOMPurify.sanitize(item.fields.nama);
                // const alamat = DOMPurify.sanitize(item.fields.alamat);
                let currentRating = item.fields.rating;

                if (currentRating === null || currentRating === undefined) {
                    currentRating = "Unrated";
                }

                htmlString += `
                <a href="/restaurant/${item.pk}" class="w-[300px] h-[300px] relative bg-[#EBE9E1] border-4 border-[#c88709] rounded-[50px] p-3 hover:shadow-2xl hover:scale-105">
                    <img src="${item.fields.foto_link}" alt="${item.fields.nama}" class="w-[235px] h-[162px] left-[35px] top-[35px] absolute rounded-[40px] object-cover"/>
                    <div class="w-[255px] left-[30px] top-[199px] absolute text-[#7c1d04] text-3xl font-['Jockey One'] leading-10 overflow-hidden whitespace-nowrap text-ellipsis">${item.fields.nama}</div>
                    <div class="w-[173px] h-[58px] left-[30px] top-[232px] absolute text-[#7c1d04] text-xl font-['Jockey One'] leading-tight overflow-hidden whitespace-nowrap text-ellipsis">${item.fields.alamat}</div>
                    <div class="w-[83.14px] left-[55px] top-[251px] absolute text-left text-[#7c1d04] text-xl font-['Jockey One'] leading-loose">${currentRating}/5</div>
                    <svg class="left-[30px] top-[259px] absolute" width="20" height="21" viewBox="0 0 32 31" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M13.9335 2.03628C14.5587 0.11203 17.281 0.112035 17.9062 2.03628L20.2183 9.15205C20.4979 10.0126 21.2998 10.5952 22.2047 10.5952H29.6866C31.7099 10.5952 32.5511 13.1843 30.9143 14.3735L24.8612 18.7713C24.1292 19.3032 23.8229 20.2459 24.1025 21.1064L26.4146 28.2222C27.0398 30.1465 24.8374 31.7466 23.2005 30.5573L17.1475 26.1595C16.4155 25.6277 15.4242 25.6277 14.6922 26.1595L8.63918 30.5573C7.00232 31.7466 4.79993 30.1465 5.42516 28.2222L7.73721 21.1064C8.01682 20.2459 7.71051 19.3032 6.97849 18.7713L0.92545 14.3735C-0.711411 13.1843 0.129825 10.5952 2.1531 10.5952H9.63506C10.5399 10.5952 11.3418 10.0126 11.6214 9.15205L13.9335 2.03628Z" fill="#EFB11D"/>
                    </svg>
                </a>
                `;
            });
        }
        document.getElementById("tempat_kuliner_cards").className = classNameString;
        document.getElementById("tempat_kuliner_cards").innerHTML = htmlString;
    }

    refreshTempatKuliner();

    async function getUserById(userId) {
        const response = await fetch(`/get-user/${userId}/`);
        return await response.json();
    }

    async function getCurrentUserId() {
        const response = await fetch("/get-current-user-id/");
        const data = await response.json();
        return data.user_id;
    }

    async function getCommunityForum(){
        return fetch("{% url 'zoya:show_json_forum' %}").then((res) => res.json())
    }

    async function refreshCommunityForum() {
        document.getElementById("forum_posts").innerHTML = "";
        const communityForum = await getCommunityForum();

        const currentUserId = await getCurrentUserId();

        let htmlString = "";

        if (communityForum.length === 0) {
            htmlString = `
                Nothing to see here...
            `;
        } else {
            for (const item of communityForum) {
                // const comment = DOMPurify.sanitize(item.fields.comment);
                // const time = DOMPurify.sanitize(item.fields.time);

                const user = await getUserById(item.fields.user);
                const isCurrentUser = String(currentUserId) === String(item.fields.user);

                // const username = DOMPurify.sanitize(user.username);

                const actionButtons = isCurrentUser
                    ? `
                    <a href="edit-forum/${item.pk}/" class="text-blue-500 hover:text-blue-700">Edit</a>
                    <button onclick="deleteForumEntry('${item.pk}')" class="text-red-500 hover:text-red-700 ml-2">Delete</button>
                    `
                    : "";


                console.log("Current User ID:", currentUserId);
                console.log("Post User ID:", item.fields.user);
                console.log("Is Current User:", isCurrentUser);
                htmlString += `
                <div class="bg-white border-l-4 border-[#c88709] p-4 rounded-[10px]">
                    <p class="text-[18px] text-darkYellow font-semibold">${user.username}</p>
                    <p class="text-[15px] text-[#7a7a7a]">${item.fields.comment}</p>
                    <span class="text-[12px] text-[#c88709]">Posted on ${item.fields.time}</span>
                    <div class="mt-2">
                        ${actionButtons}
                    </div>
                </div>
                `;
            }
        }

        document.getElementById("forum_posts").innerHTML = htmlString;
    }

    refreshCommunityForum();
</script>

{% endblock content %}