alfian/urls.py
from django.urls import path
from .views import show_main, show_json_tempat, show_json_forum, add_forum_entry_ajax, get_user_by_id, get_current_user_id, delete_forum_entry, edit_forum_entry, add_tempat_kuliner_ajax, edit_tempat_kuliner, delete_tempat_kuliner
from .views import add_makanan_ajax, edit_makanan, delete_makanan, view_tempat_makanan_admin, get_makanan_json, get_restaurant
from .views import create_resto_flutter, edit_resto_flutter, delete_resto_flutter, show_json_variasi, get_restaurant_detail
app_name = 'alfian'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('json-tempat/', show_json_tempat, name='show_json_tempat'),
    path('json-forum/', show_json_forum, name='show_json_forum'),
    path('json-variasi/', show_json_variasi, name='show_json_variasi'),
    path('edit-forum/<uuid:id>/', edit_forum_entry, name='edit_forum_entry'),
    path('delete-forum/<uuid:id>/', delete_forum_entry, name='delete_forum_entry'),
    path('create-forum-entry-ajax', add_forum_entry_ajax, name='add_forum_entry_ajax'),
    path('get-user/<int:user_id>/', get_user_by_id, name='get_user_by_id'),
    path('get-current-user-id/', get_current_user_id, name='get_current_user_id'),
    path('add-tempat-kuliner-ajax/', add_tempat_kuliner_ajax, name='add_tempat_kuliner_ajax'),
    path('edit-tempat-kuliner/<uuid:id>/', edit_tempat_kuliner, name='edit_tempat_kuliner'),
    path('delete-tempat-kuliner/<uuid:id>/', delete_tempat_kuliner, name='delete_tempat_kuliner'),
    path('add-makanan-ajax/', add_makanan_ajax, name='add_makanan_ajax'),
    path('edit-makanan/<uuid:id>/', edit_makanan, name='edit_makanan'),
    path('delete-makanan/<uuid:id>/', delete_makanan, name='delete_makanan'),
    path('view-tempat-makanan-admin/<uuid:id>/', view_tempat_makanan_admin, name='view_tempat_makanan_admin'),
    path('get-restaurant/<uuid:tempatKulinerId>/', get_restaurant, name='get_restaurant'),
    path('get-makanan-json/<uuid:tempatKulinerId>/', get_makanan_json, name='get_makanan_json'),
    path('get-resto-detail/<uuid:tempatKulinerId>/', get_restaurant_detail, name='get_restaurant_detail'),
    path('create-resto-flutter/', create_resto_flutter, name='create_resto_flutter'),
    path('edit-resto-flutter/<uuid:id>/', edit_resto_flutter, name='edit_resto_flutter'),
    path('delete-resto-flutter/<uuid:id>/', delete_resto_flutter, name='delete_resto_flutter'),
]

jajan_jogja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zoya.urls')),
    path('review/', include('reviews.urls')),
    path('search/', include('nabeel.urls')),
    path('auth/', include('main.urls')),
    path('restaurant/', include('marco.urls')),
    path('food_plans/', include('reksa.urls')),
    path('adm/', include('alfian.urls')),
    path('auth_api/', include('authentication.urls')),
]

main/urls.py
from django.urls import path, include
from main.views import show_main
from django.urls import path
from main.views import login_user, logout_user, show_main, register, profile, edit_profile_flutter

app_name = 'main'

urlpatterns = [
    path('login/', login_user, name='login_user'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
    path('profile-flutter/', edit_profile_flutter, name='profile'),
]

reviews/urls.py
from django.urls import path
from reviews.views import (
    create_review,
    get_reviews,
    delete_review,
    get_review_by_id,
    edit_review,
    user_owned_reviews,
    get_reviews_flutter,
    get_reviews_by_current_user_flutter,
    create_review_flutter,
    update_review_flutter,
    delete_review_flutter,
)

app_name = 'reviews'

urlpatterns = [
    path('<uuid:id>/create', create_review, name='create_review'),
    path('get-reviews/<str:id>/', get_reviews, name='get_reviews'),
    path('create-review-flutter/', create_review_flutter, name='create_review_flutter'),
    path('update-review-flutter/<int:id>/', update_review_flutter, name='update_review_flutter'),
    path('delete-review-flutter/<int:id>/', delete_review_flutter, name='delete_review_flutter'),
    path('get-reviews-flutter/<str:id>/', get_reviews_flutter, name='get_reviews_flutter'),
    path('get-reviews-by-current-user-flutter/', get_reviews_by_current_user_flutter, name='get_reviews_by_current_user_flutter'),
    path('delete/<int:id>/', delete_review, name='delete_review'),
    path('get-review-by-id/<int:id>/', get_review_by_id, name='get_review_by_id'),
    path('edit/<int:id>/', edit_review, name='edit_review'),
    path('', user_owned_reviews, name="my_reviews"),
    ]

alfian/models.py
from django.db import models
from zoya.models import CommunityForum, TempatKuliner, Makanan, Variasi

zoya/models.py
from django.db import models
from decimal import Decimal
import uuid
from django.contrib.auth.models import User
from django.db.models import Avg


class CommunityForum(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.DateField(auto_now_add=True)
    comment = models.TextField()

    def __str__(self):
        return self.comment

class TempatKuliner(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nama = models.CharField(max_length=255)
    description = models.TextField()
    alamat = models.CharField(max_length=255)  
    longitude = models.CharField(max_length=255)
    latitude = models.CharField(max_length=255)
    jamBuka = models.TimeField()
    jamTutup = models.TimeField()
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True, default=None)
    foto_link = models.TextField(default="https://cdn.britannica.com/36/123536-050-95CB0C6E/Variety-fruits-vegetables.jpg")
    variasi = models.ManyToManyField('Variasi', related_name='tempat_kuliner_set')

    def update_rating(self):
        result = self.reviews.aggregate(average=Avg('rating'))
        self.rating = Decimal(result['average']) if result['average'] is not None else None
        self.save()

    def __str__(self):
        return self.nama


class Makanan(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tempat_kuliner = models.ForeignKey(TempatKuliner, on_delete=models.CASCADE, related_name='makanan', null=True)
    nama = models.CharField(max_length=255)
    description = models.TextField()  
    harga = models.IntegerField()
    foto_link = models.TextField(default="https://cdn.britannica.com/36/123536-050-95CB0C6E/Variety-fruits-vegetables.jpg")

    def __str__(self):
        return self.nama
    

class Variasi(models.Model):
    nama = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.nama

alfian/forms.py
# admin/forms.py
from django import forms
from zoya.models import TempatKuliner, Makanan

class TempatKulinerForm(forms.ModelForm):
    class Meta:
        model = TempatKuliner
        fields = ['nama', 'description', 'alamat', 'longitude', 'latitude', 'jamBuka', 'jamTutup', 'rating', 'foto_link', 'variasi']

class MakananForm(forms.ModelForm):
    class Meta:
        model = Makanan
        fields = ['tempat_kuliner', 'nama', 'description', 'harga', 'foto_link']

alfian/views.py
import json
from django.shortcuts import get_object_or_404, redirect, render, reverse
from reviews.models import Review
from zoya.models import TempatKuliner, CommunityForum, Makanan, Variasi
from zoya.forms import CommunityForumForm
from .forms import TempatKulinerForm, MakananForm
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_http_methods
from django.utils.html import strip_tags
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required

@staff_member_required
@login_required(login_url='main:login_user')
def show_main(request):
    makanan = Makanan.objects.all()[:15]
    variasi = Variasi.objects.all()

    context = {
        'makanan': makanan,
        'variasi': variasi,
    }

    return render(request, 'landing_admin.html', context)



def show_json_tempat(request):
    data = TempatKuliner.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_forum(request):
    data = CommunityForum.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_forum_by_id(request, id):
    data = CommunityForum.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
@require_http_methods(["DELETE"])
@login_required(login_url='main:login_user')
@staff_member_required
def delete_forum_entry(request, id):
    if request.user.is_authenticated:
        try:
            forum_entry = CommunityForum.objects.get(pk=id, user=request.user)
            forum_entry.delete()
            return HttpResponse(status=204)
        except CommunityForum.DoesNotExist:
            return HttpResponse(status=404)
    return HttpResponse(status=403)

@login_required(login_url='main:login_user')
@staff_member_required
def edit_forum_entry(request, id):
    mood = CommunityForum.objects.get(pk=id)
    form = CommunityForumForm(request.POST or None, instance=mood)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('alfian:show_main'))

    context = {'form': form}
    return render(request, "edit_forum.html", context)

@csrf_exempt
@require_POST
@login_required(login_url='main:login_user')
@staff_member_required
def add_forum_entry_ajax(request):
    comment = strip_tags(request.POST.get("comment"))
    user = request.user

    new_forum = CommunityForum(
        comment=comment,
        user=user
    )
    new_forum.save()

    return HttpResponse(b"CREATED", status=201)

@login_required(login_url='main:login_user')
@staff_member_required
def get_user_by_id(request, user_id):
    user = User.objects.get(pk=user_id)
    data = {
        "username": user.username,
    }
    return JsonResponse(data)

@login_required(login_url='main:login_user')
@staff_member_required
def get_current_user_id(request):
    if request.user.is_authenticated:
        return JsonResponse({'user_id': request.user.id})
    else:
        return JsonResponse({'user_id': None})

@require_POST
@login_required(login_url='main:login_user')
@staff_member_required
def add_tempat_kuliner_ajax(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden("You do not have permission to perform this action.")
    
    nama = strip_tags(request.POST.get("nama"))
    description = strip_tags(request.POST.get("description"))
    alamat = strip_tags(request.POST.get("alamat"))
    longitude = request.POST.get("longitude")
    latitude = request.POST.get("latitude")
    jamBuka = request.POST.get("jamBuka")
    jamTutup = request.POST.get("jamTutup")
    rating = request.POST.get("rating")
    foto_link = request.POST.get("foto_link")

    new_tempat_kuliner = TempatKuliner(
        nama=nama,
        description=description,
        alamat=alamat,
        longitude=longitude,
        latitude=latitude,
        jamBuka=jamBuka,
        jamTutup=jamTutup,
        rating=rating,
        foto_link=foto_link
    )
    new_tempat_kuliner.save()

    return HttpResponse(b"CREATED", status=201)


@staff_member_required
@login_required(login_url='main:login_user')
@staff_member_required
def edit_tempat_kuliner(request, id):
    tempat = get_object_or_404(TempatKuliner, pk=id)
    form = TempatKulinerForm(request.POST or None, instance=tempat)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('alfian:show_main')
    else:
        print("Form is not valid")
        print(form.errors)
    context = {
        'form': form,  # Ensure this is a form object
        'tempat_kuliner': tempat,
    }
    return render(request, "edit_tempat_kuliner.html", context)

@require_http_methods(["DELETE"])
@login_required(login_url='main:login_user')
@staff_member_required
def delete_tempat_kuliner(request, id):
    try:
        tempat = TempatKuliner.objects.get(pk=id)

        if not (request.user.is_staff or request.user.is_superuser) :
            return HttpResponse(status=403)
        
        tempat.delete()
        return HttpResponse(status=204)
    except TempatKuliner.DoesNotExist:
        return HttpResponse(status=404)
    
@require_POST
@login_required(login_url='main:login_user')
@staff_member_required
def add_makanan_ajax(request):
    tempat_kuliner = strip_tags(request.POST.get("tempat_kuliner")) 
    nama = strip_tags(request.POST.get("nama"))
    description = strip_tags(request.POST.get("description"))
    harga = request.POST.get("harga")
    foto_link = request.POST.get("foto_link")

    new_makanan = Makanan (
        tempat_kuliner=tempat_kuliner,
        nama=nama,
        description=description,
        harga=harga,
        foto_link=foto_link
    )
    new_makanan.save()
    return HttpResponse(b"CREATED", status=201)

@login_required(login_url='main:login_user')
@staff_member_required
def edit_makanan(request, id):
    makanan = get_object_or_404(Makanan, pk=id)
    form = MakananForm(request.POST or None, instance=makanan)


    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('alfian:show_main'))
    
    else:
        print("Form is not valid")
        print(form.errors)

    context = {'form': form,
               'makanan': makanan,
               }
    return render(request, "edit_makanan.html", context)


@login_required(login_url='main:login_user')
@staff_member_required
def delete_makanan(request, id):
    makanan = get_object_or_404(Makanan, pk=id)
    makanan.delete()
    return redirect('alfian:show_main')
    
@login_required(login_url='main:login_user')
@staff_member_required
def view_tempat_makanan_admin(request, id):
    tempat = get_object_or_404(TempatKuliner, pk=id)
    return render(request, 'index_admin.html', {'restoran': tempat})

@login_required(login_url='main:login_user')
@staff_member_required
def get_restaurant(request, tempatKulinerId):
    tempat_kuliner = get_object_or_404(TempatKuliner, pk=tempatKulinerId)
    has_reviewed = Review.objects.filter(user=request.user.id,tempat_kuliner=tempat_kuliner).exists()
    context = {'restoran':tempat_kuliner, 'username':request.user.username, 'restaurant_id':tempat_kuliner.id, 'has_reviewed':has_reviewed}
    return render(request, "restaurant/index.html", context)


@login_required(login_url='main:login_user')
@staff_member_required
def get_makanan_json(request, tempatKulinerId):
    tempat_kuliner = get_object_or_404(TempatKuliner, pk=tempatKulinerId)
    semua_makanan = Makanan.objects.filter(tempat_kuliner=tempat_kuliner)
    return HttpResponse(serializers.serialize("json", semua_makanan), content_type="application/json")

@csrf_exempt
def get_restaurant_detail(request, tempatKulinerId):
    try:
        # Ambil data restoran berdasarkan UUID
        tempat_kuliner = get_object_or_404(TempatKuliner, pk=tempatKulinerId)
        
        data = {
            "id": str(tempat_kuliner.id),
            "nama": tempat_kuliner.nama,
            "description": tempat_kuliner.description,
            "alamat": tempat_kuliner.alamat,
            "longitude": tempat_kuliner.longitude,
            "latitude": tempat_kuliner.latitude,
            "jamBuka": tempat_kuliner.jamBuka.strftime("%H:%M"),
            "jamTutup": tempat_kuliner.jamTutup.strftime("%H:%M"),
            "rating": str(tempat_kuliner.rating) if tempat_kuliner.rating else None,
            "foto_link": tempat_kuliner.foto_link,
            "variasi": [{"id": variasi.id, "nama": variasi.nama} for variasi in tempat_kuliner.variasi.all()],
        }
        return JsonResponse({"status": "success", "data": data}, status=200)
    except ValueError:
        return JsonResponse({"status": "error", "message": "Invalid ID format"}, status=400)
    except TempatKuliner.DoesNotExist:
        return JsonResponse({"status": "error", "message": "Data not found"}, status=404)


@csrf_exempt
def create_resto_flutter(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return JsonResponse({"status": "error", "message": "You must be logged in to create a resto."}, status=403)
        if not request.user.is_superuser:
            return JsonResponse({"status": "error", "message": "You must be an admin to create a resto."}, status=403)

        data = json.loads(request.body)
        user=request.user
        comment=data["comment"]

        if not comment or comment == "":
            return JsonResponse({"status": "error", "message": "All fields must be filled."}, status=400)

        new_resto = TempatKuliner.objects.create(
            user=user,
            comment=comment
        )

alfian/templates/edit_makanan.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-white">
    <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
        <h1 class="py-5 text-3xl font-bold text-center text-darkOrange">Edit Makanan</h1>

        <div class="bg-white rounded-[40px] p-6 form-style border-4 border-darkOrange">
            <form method="POST" enctype="multipart/form-data" action="{% url 'alfian:edit_makanan' makanan.id %}">
                {% csrf_token %}

                <!-- Nama -->
                <div class="flex flex-col mb-4">
                    <label for="id_nama" class="font-semibold text-darkOrange text-2xl">Nama</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.nama|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.nama.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.nama.help_text }}</p>
                    {% endif %}
                    {% for error in form.nama.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Deskripsi -->
                <div class="flex flex-col mb-4">
                    <label for="id_description" class="font-semibold text-darkOrange text-2xl">Deskripsi</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.description|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.description.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.description.help_text }}</p>
                    {% endif %}
                    {% for error in form.description.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Harga -->
                <div class="flex flex-col mb-4">
                    <label for="id_harga" class="font-semibold text-darkOrange text-2xl">Harga</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.harga|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.harga.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.harga.help_text }}</p>
                    {% endif %}
                    {% for error in form.harga.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Link Foto -->
                <div class="flex flex-col mb-4">
                    <label for="id_foto_link" class="font-semibold text-darkOrange text-2xl">Link Foto</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.foto_link|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.foto_link.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.foto_link.help_text }}</p>
                    {% endif %}
                    {% for error in form.foto_link.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Tempat Kulier -->
                <div class="flex flex-col mb-4">
                    <label for="id_tempat_kuliner" class="font-semibold text-darkOrange text-2xl">Tempat Kuliner</label>
                    {{ form.tempat_kuliner }}
                </div>

                <!-- Tombol Cancel dan Save -->
                <div class="flex flex-row space-x-4">
                    <a href="{% url 'alfian:show_main' %}" class="bg-orange text-white text-[18px] py-2 rounded-[10px] hover:bg-darkOrange w-1/2 text-center">Cancel</a>
                    <button type="submit" class="bg-yellow text-white text-[18px] py-2 rounded-[10px] hover:bg-darkYellow w-1/2">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

alfian/templates/edit_tempat_kuliner.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}

{% block content %}
{% include 'navbar.html' %}

<div class="flex flex-col min-h-screen bg-white">
    <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
        <h1 class="py-5 text-3xl font-bold text-center text-darkOrange">Edit Tempat Kuliner</h1>

        <div class="bg-white rounded-[40px] p-6 form-style border-4 border-darkOrange">
            <form method="POST" enctype="multipart/form-data" action="{% url 'alfian:edit_tempat_kuliner' tempat_kuliner.id %}">
                {% csrf_token %}

                <!-- Nama -->
                <div class="flex flex-col mb-4">
                    <label for="id_nama" class="font-semibold text-darkOrange text-2xl ">Nama</label>
                    <div class="w-full flex flex-col py-3 bg-white">
                        {{ form.nama|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.nama.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.nama.help_text }}</p>
                    {% endif %}
                    {% for error in form.nama.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Deskripsi -->
                <div class="flex flex-col mb-4">
                    <label for="id_description" class="font-semibold text-darkOrange text-2xl">Deskripsi</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.description|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.description.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.description.help_text }}</p>
                    {% endif %}
                    {% for error in form.description.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Alamat -->
                <div class="flex flex-col mb-4">
                    <label for="id_alamat" class="font-semibold text-darkOrange text-2xl">Alamat</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.alamat|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.alamat.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.alamat.help_text }}</p>
                    {% endif %}
                    {% for error in form.alamat.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Longitude -->
                <div class="flex flex-col mb-4">
                    <label for="id_longitude" class="font-semibold text-darkOrange text-2xl">Longitude</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.longitude|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.longitude.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.longitude.help_text }}</p>
                    {% endif %}
                    {% for error in form.longitude.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Latitude -->
                <div class="flex flex-col mb-4">
                    <label for="id_latitude" class="font-semibold text-darkOrange text-2xl">Latitude</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.latitude|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.latitude.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.latitude.help_text }}</p>
                    {% endif %}
                    {% for error in form.latitude.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Jam Buka -->
                <div class="flex flex-col mb-4">
                    <label for="id_jamBuka" class="font-semibold text-darkOrange text-2xl">Jam Buka</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.jamBuka|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.jamBuka.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.jamBuka.help_text }}</p>
                    {% endif %}
                    {% for error in form.jamBuka.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Jam Tutup -->
                <div class="flex flex-col mb-4">
                    <label for="id_jamTutup" class="font-semibold text-darkOrange text-2xl">Jam Tutup</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.jamTutup|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.jamTutup.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.jamTutup.help_text }}</p>
                    {% endif %}
                    {% for error in form.jamTutup.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Rating -->
                <div class="flex flex-col mb-4">
                    <label for="id_rating" class="font-semibold text-darkOrange text-2xl">Rating</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.rating|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.rating.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.rating.help_text }}</p>
                    {% endif %}
                    {% for error in form.rating.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Link Foto -->
                <div class="flex flex-col mb-4">
                    <label for="id_foto_link" class="font-semibold text-darkOrange text-2xl">Link Foto</label>
                    <div class="w-full flex flex-col py-3">
                        {{ form.foto_link|add_class:"placeholder-white-500 bg-white border-darkYellow border-4 rounded-lg px-2" }}
                    </div>
                    {% if form.foto_link.help_text %}
                        <p class="mt-1 text-sm text-grey">{{ form.foto_link.help_text }}</p>
                    {% endif %}
                    {% for error in form.foto_link.errors %}
                        <p class="mt-1 text-sm text-orange">{{ error }}</p>
                    {% endfor %}
                </div>

                <!-- Variasi -->
                <div class="flex flex-col mb-4">
                    <label for="id_variasi" class="font-semibold text-darkOrange text-2xl">Variasi</label>
                    {{ form.variasi }}
                </div>

                <div class="flex flex-row space-x-4">
                    <a href="{% url 'alfian:show_main' %}" class="bg-orange text-white text-[18px] py-2 rounded-[10px] hover:bg-darkOrange w-1/2 text-center">Cancel</a>
                    <button type="submit" class="bg-yellow text-white text-[18px] py-2 rounded-[10px] hover:bg-darkYellow w-1/2">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}