jajan_jogja/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('zoya.urls')),
    path('review/', include('reviews.urls')),
    path('search/', include('nabeel.urls')),
    path('auth/', include('main.urls')),
    path('restaurant/', include('marco.urls')),
    path('food_plans/', include('reksa.urls')),
    path('adm/', include('alfian.urls')),
    path('auth_api/', include('authentication.urls')),
]

main/urls.py
from django.urls import path, include
from main.views import show_main
from django.urls import path
from main.views import login_user, logout_user, show_main, register, profile, edit_profile_flutter

app_name = 'main'

urlpatterns = [
    path('login/', login_user, name='login_user'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('profile/', profile, name='profile'),
    path('profile-flutter/', edit_profile_flutter, name='profile'),
]

zoya/urls.py
from django.urls import path
from zoya.views import show_main, show_json_tempat, show_json_forum, add_forum_entry_ajax, get_user_by_id, get_current_user_id, delete_forum_entry, show_json_makanan, edit_forum_entry, create_forum_flutter, edit_forum_flutter, delete_forum_flutter, show_json_user_by_id, show_json_current_user, show_json_forum_by_id

app_name = 'zoya'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('json-tempat/', show_json_tempat, name='show_json_tempat'),
    path('json-forum/', show_json_forum, name='show_json_forum'),
    path('json-forum/<uuid:id>/', show_json_forum_by_id, name='show_json_forum_by_id'),
    path("json-makanan/", show_json_makanan, name="show_json_makanan"),
    path('edit-forum/<uuid:id>/', edit_forum_entry, name='edit_forum_entry'),
    path('delete-forum/<uuid:id>/', delete_forum_entry, name='delete_forum_entry'),
    path('create-forum-entry-ajax', add_forum_entry_ajax, name='add_forum_entry_ajax'),
    path('get-user/<int:user_id>/', get_user_by_id, name='get_user_by_id'),
    path('json-user/<int:user_id>/', show_json_user_by_id, name='show_json_user_by_id'),
    path('get-current-user-id/', get_current_user_id, name='get_current_user_id'),
    path('json-current-user/', show_json_current_user, name='show_json_current_user'),
    path('create-flutter/', create_forum_flutter, name='create_forum_flutter'),
    path('edit-flutter/<uuid:forum_id>/', edit_forum_flutter, name='edit_forum_flutter'),
    path('delete-flutter/<uuid:forum_id>/', delete_forum_flutter, name='delete_forum_flutter'),
]

main/views.py
import datetime
import json
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from zoya.views import show_main
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("zoya:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
    else:
       form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login_user')
    context = {'form':form}
    return render(request, 'register.html', context)

def logout_user(request):
    response = HttpResponseRedirect(reverse('zoya:show_main'))
    response.delete_cookie('last_login')
    logout(request)
    return response

@login_required(login_url='main:login_user')
def profile(request):
    user = request.user
    
    if request.method == 'POST':
        username = request.POST.get('name')
        email = request.POST.get('email')
        if username:
            if User.objects.filter(username=username).exclude(pk=user.pk).exists():
                messages.error(request, "Username already taken.")
            else:
                if email:
                    user.username = username
                    user.email = email
                    user.save()
                    return redirect('main:profile')

    context = {
        'user': user,
    }
    return render(request, 'profile.html', context)

@csrf_exempt
def edit_profile_flutter(request):
    if request.method == "POST":
        if not request.user.is_authenticated:
            return JsonResponse({"status": "error", "message": "You must be logged in to create a forum."}, status=403)

        data = json.loads(request.body)
        username=data["username"]
        email=data["email"]

        if not username or username == "" or not email or email == "":
            return JsonResponse({"status": "error", "message": "All fields must be filled."}, status=400)

        user = request.user

        if username:
            if User.objects.filter(username=username).exclude(pk=user.pk).exists():
                return JsonResponse({"status": "error", "message": "Username already taken."}, status=402)
            else:
                if email:
                    user.username = username
                    user.email = email
                    user.save()
                    return JsonResponse({"status": "success", "message": "Comment successfully edited."}, status=200)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method."}, status=400)

main/templates/index.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" with page="home" user=user%}
{% endblock content %}

main/templates/login.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" with page="login"%}
<main class="w-full flex flex-col items-center gap-6 sm:pt-28 bg-white h-full justify-center">
    <section class="z-10">
      <h1 class="text-center text-4xl sm:text-5xl">Welcome Back!!!</h1>
      <p class="text-center text-lg sm:text-xl">Please enter login details below!</p>
    </section>
    <section class="w-[80%]  bg-white border-2 border-darkOrange rounded-[2rem] flex flex-col px-5 pb-4 pt-5 justify-center max-w-80 z-10">
      <form class="flex flex-col gap-7 px-4" method="POST" action="">
        {% csrf_token %}
        <div class="rounded-md shadow-sm flex flex-col gap-3">
          <div>
            <label for="username" class="ml-3 text-xl">Username</label>
            <input id="username" name="username" type="text" required class="relative block w-full px-3 py-2 border-2 rounded-xl bg-white focus:border-2 
            border-darkOrange
            focus:outline-none
            focus:border-darkYellow  sm:text-sm text-lg" placeholder="Username">
          </div>
          <div>
            <label for="password" class="ml-3 text-xl">Password</label>
            <div>
              <input id="password" name="password" type="password" required class="relative block w-full px-3 py-2 border-2 rounded-xl bg-white focus:border-2 
            border-darkOrange focus:outline-none focus:border-darkYellow  sm:text-sm text-lg" placeholder="Password">
            </div>
          </div>
        </div>
        <div class="flex gap-2">
          <a href="{% url "zoya:show_main" %}" class="w-full h-10 border-2 border-yellow text-darkYellow rounded-2xl text-lg flex justify-center items-center hover:scale-105">
            Back
          </a>
          <button type="submit" class="w-full h-10 border-2 border-yellow bg-yellow text-white rounded-2xl text-lg hover:scale-105">
            Sign in
          </button>
        </div>
      </form>
      <div>
        <p class="text-center">Don't have an account yet? <a href="{% url "main:register" %}" class="text-orange">sign up here</a></p>
      </div>
    </section>
    <div class="absolute w-[350px] h-[350px] rounded-full opacity-[0.6] bg-orange blur-[98.27586364746094px] z-0"></div>
</main>
{% endblock content %}

main/templates/profile.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" with page="profile" user=user%}

<div class="w-full h-full p-4 flex justify-center items-center">
  <div class="w-80 h-fit p-6 border-2 border-darkOrange rounded-3xl shadow-[0_0_20px_rgb(124,_29,_5,_0.5)]">
    <h1 class="text-black text-3xl text-center">Profile</h1>
    <form id="profileForm" method="POST" action="{% url 'main:profile' %}"> 
      {% csrf_token %}
        <div class="space-y-2 mb-12">
          <div>
            <label for="name" class="pl-2 text-darkOrange text-xl">Nama</label>
            <input id="name" name="name" type="text" disabled required value='{{ user.username }}' class="relative block w-full px-3 py-2 border-2 rounded-xl bg-white focus:border-2 border-darkOrange focus:outline-none focus:border-darkYellow sm:text-sm text-lg disabled:text-grey" placeholder="username">
          </div>
          <div>
            <label for="email" class="pl-2 text-darkOrange text-xl">Email</label>
            <input id="email" name="email" type="email" disabled value='{{ user.email }}' class="relative block w-full px-3 py-2 border-2 rounded-xl bg-white focus:border-2 border-darkOrange focus:outline-none focus:border-darkYellow sm:text-sm text-lg disabled:text-grey">
          </div>
        </div>
        <div id="editCard" class="flex justify-between items-center gap-4">
          <button id="back" type="button" onclick="window.location='/'" class="w-full text-lg text-darkYellow bg-white px-8 py-1 border-2 border-yellow rounded-xl hover:scale-105">Back</button>
          <button id="edit" onclick="editProfile()" class="w-full text-lg text-white bg-yellow px-8 py-1 border-2 border-yellow rounded-xl hover:scale-105">Edit</button>
        </div>
    </form>
  </div>
</div>

<script>
function editProfile() {
  document.getElementById("name").disabled = false;
  document.getElementById("email").disabled = false;
  document.getElementById("editCard").innerHTML = `
      <button id="cancel" onclick="cancelButton()" class="w-full text-lg text-white bg-orange px-8 py-1 border-2 border-orange rounded-xl">Cancel</button>
      <button id="save" type="submit" class="w-full text-lg text-white bg-yellow px-8 py-1 border-2 border-yellow rounded-xl">Save</button>
  `
}

function cancelButton() {
  document.getElementById("name").disabled = true;
  document.getElementById("email").disabled = true;
  document.getElementById("editCard").innerHTML = `
    <button id="back" type="button" onclick="window.location='/'" class="w-full text-lg text-darkYellow bg-white px-8 py-1 border-2 border-yellow rounded-xl">Back</button>
    <button id="edit" onclick="editProfile()" class="w-full text-lg text-white bg-yellow px-8 py-1 border-2 border-yellow rounded-xl">Edit</button>
`
}
</script>
{% endblock content %}

main/templates/register.html
{% extends "base.html" %}
{% block content %}
{% include "navbar.html" with page="login"%}
<main class="w-full flex flex-col items-center gap-6 sm:pt-28 bg-white h-full justify-center">
    <style>
        form input{
            width: 100%;
            padding-top: 0.25rem;
            padding-bottom: 0.25rem;
            border-radius: 0.75rem;
            border: 2px solid #7c1d05;
            background-color: white;
            padding-left: 0.75rem;
            padding-right: 0.75rem;
          }
          
          form input:focus {
            outline: none;
            border: 2px solid #c98809;
          }
    </style>
    <section class="z-10">
      <h1 class="text-center text-4xl sm:text-5xl">Create an Account</h1>
      <p class="text-center text-lg sm:text-xl">Please enter account details below!</p>
    </section>
    <section class="w-[80%] bg-white border-2 border-darkOrange rounded-[2rem] flex flex-col px-5 pb-4 pt-5 justify-center max-w-80 z-10">
      <form class="space-y-5 px-4" method="POST">
        {% csrf_token %}
        <input type="hidden" name="remember" value="true">
        <div class="rounded-md shadow-sm flex flex-col gap-1">
          {% for field in form %}
            <div class="{% if not forloop.first %}{% endif %}">
              <label for="{{ field.id_for_label }}" class="ml-3 text-xl">
                {{ field.label }}
              </label>
              <div class="relative">
                {{ field }}
                <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                  {% if field.errors %}
                    <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                    </svg>
                  {% endif %}
                </div>
              </div>
              {% if field.errors %}
                {% for error in field.errors %}
                  <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>
          {% endfor %}
        </div>

        <div class="flex gap-2">
            <a href="{% url "zoya:show_main" %}" class="w-full h-10 border-2 border-yellow text-darkYellow rounded-2xl text-lg flex justify-center items-center hover:scale-105">
                Back
            </a>
            <button type="submit" class="w-full h-10 border-2 border-yellow bg-yellow text-white rounded-2xl text-lg hover:scale-105">
                Register
            </button>

        </div>
      </form> 
      <div>
        <p class="text-center">Already have an account yet? <a href="{% url "main:login_user" %}" class="text-orange">sign in here</a></p>
      </div>
    </section>
    <div class="absolute w-[350px] h-[350px] rounded-full opacity-[0.6] bg-orange blur-[98.27586364746094px] z-0"></div>
</main>
{% endblock content %}